branch-defaults:
  master:
    environment: Telos-Admin-Meeting-dev
    group_suffix: null
  production:
    environment: Telos-Admin-Meeting-production
  staging:
    environment: Telos-Admin-Meeting-dev
environment-defaults:
  Telos-Admin-Meeting-dev:
    branch: null
    repository: null
  Telos-Admin-Meeting-production:
    branch: null
    repository: null
global:
  application_name: Telos-Admin-Meeting
  branch: null
  default_ec2_keyname: telos-prod
  default_platform: node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
